updated condition

diff --git a/.github/workflows/provision-nonprod.yml b/.github/workflows/provision-nonprod.yml
--- a/.github/workflows/provision-nonprod.yml
+++ b/.github/workflows/provision-nonprod.yml
@@ -41,5 +41,15 @@ jobs:
       # Run terragrunt provision
       - name: Terragrunt Provision
         run: |
-          cd environments
-          terragrunt run-all apply -auto-approve -terragrunt-non-interactive
+          if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
+            cd environments
+            terragrunt run-all destroy -auto-approve -terragrunt-non-interactive
+          fi
+          if [[ "${{ github.event.inputs.destroy }}" == "false" ]]; then
+            cd environments
+            terragrunt run-all apply -auto-approve -terragrunt-non-interactive
+          fi
+          if [[ "${{ github.event.inputs.destroy }}" != "true" && "${{ github.event.inputs.destroy }}" != "false" ]]; then
+            echo "Error: destroy must be 'true' or 'false'"
+            exit 1
+          fi
